travis:
  secure:
    BINSTAR_TOKEN: KAnULGrS5/MnYhrwxt2ncE9Jb9OZ0tl/0FN9hoXrDEziAVUIr9XVpvr+UgVJGl+ItybYIX4vbAKfmiackUGdT97YwTzU42kI6btQwQSVWIPp0n/jpm9m4O3QLwD3BmzC7+JwlkkrM5/LTF3CTAoDedkw7p7NghqhYrU5TFF+dluoYr+k7AcIidMB+4bSZkFx1HKRvcXkeiBWVA2n1FvJoCP1tjrS/5VSK5WfxWl5JbkOxTkV7PiAYR8W3PtlHNymVj2sx2v3XkMH0TYd2INaoUN98kSC8P3ct01WkuEaUrcaIzYcLu3kDcdpEzCcunSs9laGvHTe9QCv9o2Si+fPpYhQDItmobQ1Zawsc4eLpBdSAUkEA6CSpggh+v/SfszM4qd9KcJuB7a8IlPFngXO7pahTnCzfh2Vf6u7daSZdZe2clOcBlQJQqopks1a0rH/YpiFc7Y5IO2xaQbEpA5NZzsj6/2hxtpcHhJ0vIZYMMgSk548gBWl49c1aspZoaKSB7Mc2dKmpjYizHNz2p7sh12Dvjzp7f/rl/HAhldBojQYA+Ov3LTJedK02ADGolTaI+/8GOzfVACRBqOqQDroXlmirYtHCdXGKdpmQx2BSpaS0DTdj52ZZgAQFjYOPrDpeAvSi9SgejrGJ8zn7Eafl97vB8lgSW/JzBFRKXzmAuU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
