travis:
  secure:
    BINSTAR_TOKEN: RiZoJR9uxw9+ezFf1fcStEM1EQfkCcup3JAzLCdhArqxYofGqxMZTYdORFIyU/vWy566X2lvVGxfc3T7Jj2CVBeTuQnIt1lET5YzkPHFuBs3OYmIq3o1TIp7uJb+jD8/3zR5jRR1PHmZI+Fu8k0VByrtD5CjK7bdXbaHIn616GgfDWYS+pAeX/iz+vaWTho3uAUyYVno6ErlFviTJXD3kB488SmwWF6W9G67Wp/3/goBCNm/VqNNieiE0XdRZnbBUbvMXdnzU2a4uUx4lvhnCfcClnH4AbfSrfvm0J/9MxkNzpJp1ge722r4IxDuMHlFPDoEiOjbdbf5WR3+0nMbE0fexzr03pkq8e+3VPT9/DbpDM0mfa6dw7U5AII+9CLvsQsvMK1CwQRs0WSiCrR0h59dvVrU7izZY0RfsUvT5Wuja1k1AbFDDbhegI9whbAjNh4s6FK8xE8m060lITTf7CN8U4JIV0Lj+1Df9ggnoX7gBgw0KQ+ktAdHCytn00TxJbhVUD4jAHzo38cbnYv3APMZJSQ8qIZ9hAwaDaMO0z6AsSesfHS3H7I+H8V86+gzefg1EtDue4Z40usCIJUlzi41wPrHsraichmUWZvjm/ZsREOdJbdGWohAJsym224ZVUILDG6ivuuErvaZaOG7/LR6sMtSzhU1646A0ro5xmc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
